### ISSUE TITLE
Why delete code on ogb-products 

### ISSUE THREAD

**Issue by saladcat** [acbull/pyHGT#11]
Thanks for sharing your awesome works.
I notice your methods has gained a great improvement on ogb-products, but you delete it suddenly? There are any problems with the code of ogb-products code?

**Comment by acbull** [comment]
Sorry, in my previous submission, the sampling process may incorporate implicit information leakage, so I temporarily remove the code and will release later when the bug is fixed.

**Comment by saladcat** [comment]
get it, thank you!
