### ISSUE TITLE
Hyper-parameters to reproduce results in paper

### ISSUE THREAD

**Issue by lingfanyu** [acbull/pyHGT#14]
Hi, could you share the hyper-parameters you used to train paper-venue and paper-field for graph_CS which can reproduce results in the paper? 

I downloaded graph_CS.pk and ran `python train_paper_venue.py` which used default parameters in the code. The results I got was:
Best Test NDCG: 0.4332
Best Test MRR:  0.2547

Thanks!

**Comment by acbull** [comment]
Hi:

The hyper-parameter on the paper is --n_hid 256 --n_layer 3 . If the memory permits, the higher sample_width, and sample_depth are the better. 

I tried such setting:

''
python train_paper_venue.py  --n_hid 256 --n_layer 3 --batch_size 512 --sample_width 256
''

and get the result: 

Best Test NDCG: 0.4434
Best Test MRR:  0.5164

**Comment by lingfanyu** [comment]
Thanks for the reply! 

In the paper, for paper_venue classification on graph_CS, the reported NDCG is .473±.054, and MRR is .288±.088 (0.5164 might be a typo?). What was the sample_width and sample_depth to achieve this result? And how much CPU/GPU memory did you have?

**Comment by acbull** [comment]
Oh sorry. The result I send is for paper_field. As reported, sample_width=256 and sample_depth=6.
