### ISSUE TITLE
Some problems about running code 

### ISSUE THREAD

**Issue by wjlpku** [acbull/pyHGT#2]
Hi, when I run 
`python3 train_paper_field.py --data_dir ../data --model_dir ./model_save --conv_name hgt`
Some errors happened as follow
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/wangjialin/anaconda3/envs/pyG/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "train_paper_field.py", line 96, in node_classification_sample
    target_ids = np.random.choice(list(pairs.keys()), batch_size, replace = False)
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_paper_field.py", line 227, in <module>
    train_data = [job.get() for job in jobs[:-1]]
  File "train_paper_field.py", line 227, in <listcomp>
    train_data = [job.get() for job in jobs[:-1]]
  File "/home/wangjialin/anaconda3/envs/pyG/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: 'a' cannot be empty unless no samples are taken
```
It seems like some errors about multiprocessing, Can you give me some suggestions?

**Comment by xcfcode** [comment]
Hi, just choose another file to run. I download the data **graph_NN.pk.**
Run `python train_paper_field.py --data_dir ./data/ --model_dir ./model/ --conv_name hgt`

---

when I run `python train_author_disambiguation.py --data_dir ./data/ --model_dir ./model/ --conv_name hgt`, I meet the same error, maybe due to the data format.

**Comment by wjlpku** [comment]
> Hi, just choose another file to run. I download the data **graph_NN.pk.**
> Run `python train_paper_field.py --data_dir ./data/ --model_dir ./model/ --conv_name hgt`
> 
> when I run `python train_author_disambiguation.py --data_dir ./data/ --model_dir ./model/ --conv_name hgt`, I meet the same error, maybe due to the data format.

Thanks for your advice,  while I download the data **graph_NN.pk**, and Run
`python train_paper_field.py --data_dir ../data/ --model_dir ./model_save/ --conv_name hgt` and I get the error mentioned above, I also **train_paper_venue.py** and get the same problem.

**Comment by xcfcode** [comment]
Have you renamed the file to graph_cs.pk?
And I also set n_pool to 1 and cuda to -1 (cpu only).
You can have a try.

**Comment by acbull** [comment]
Sorry for the trouble. The graph_NN and graph_ML files indeed lack an important field. I've updated these two files as well as the code a week ago.  Can you download the latest file and try again?

**Comment by xcfcode** [comment]
I also delete the parameter **node_num** in message(), is this the right thing to run the code? Since I find it is not very useful to run the code and there is no use about **node_num** in the func.
Thanks a lot! 😃

**Comment by wjlpku** [comment]
Thanks for your relpy, I will try to download the new processed data~

**Comment by xcfcode** [comment]
@wjlpku @acbull Have you met the problem that **num_nodes** in the message passing function is empty?
