### ISSUE TITLE
OGBN-MAG problem

### ISSUE THREAD

**Issue by xjtuwxliang** [acbull/pyHGT#22]
Thanks for your open source code. I have a question to ask you. 

When I use the pre training model you provided on the ogbn MAG dataset, the accuracy of eval is only 0.39. I want to know what the problem is and how to reproduce your accuracy of 0.50?

the command I run is `python eval_ogbn_mag.py --prev_norm --last_norm --use_RTE`，the ogb version is 1.2.1。

**Comment by xjtuwxliang** [comment]
It is solved. I ran the train code and the results can be reproduced. The pre-training model you provided may not be right, hhh. . .

**Comment by acbull** [comment]
Sorry about that. I'll check the pre-trained model asap.
