### ISSUE TITLE
A doubt about meta-relationship

### ISSUE THREAD

**Issue by Luokejin** [acbull/pyHGT#23]
Thanks for your inspiring work.
I have begun to learn something about heterogeneous network recently. And when I contrast the meta-relationship in this paper with the triplet relation in Knowledge Graph, I feel confused about the difference between them.  Even I can't make a distinction between the meta-path's method with the meta-relation's, when the input of their model both are some adjacency matrixs and nodes. Where does the meta-path function appear in model ?
I have to admit that these questions looks ridiculous, but still waiting your answer. Thanks.

**Comment by acbull** [comment]
The concepts of meta relation and meta path are indeed similar to the KG triplet. The main difference of KG and heterogeneous graphs, from my understanding, is that the node of KG doesn't have too many rich features, and people have to use their concrete type to determine their meaning. While for heterogeneous graph, each node still have a feature with a type, and type is only helpful to better represent these nodes.


My labmate has a paper that combines these two concepts to get better KG representation: https://dl.acm.org/doi/pdf/10.1145/3292500.3330838, probably it can help you understand the difference better.

**Comment by Luokejin** [comment]
I have to apologize for interrupt you again. I got a new problem with your code  :(
When I run the code, it occurred an error like that:
`IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)`

I also tracked  the function of **propagate()**  from the source code of **class messagepassing()** under torch.geometric.nn.
But I feel sorry about that I can't understand the problem function **self.__collect__()**  on function propagate().

I have checked my dataset shape as ,
`print(node_feature.shape)  # torch.Size([1602, 50])
print(node_type.shape)  # torch.Size([1602])
print(edge_time.shape)  # torch.Size([675680])
print(edge_type.shape)  # torch.Size([675680])
print(edge_index.shape) torch.Size([2, 675680])`

but I still can't figure out what's main problem. May you know how to solve this problem? Thank you very much.

**Comment by acbull** [comment]
It is due to the pytorch_geometric version. Please utilize exactly the same environment as we provide.

**Comment by Luokejin** [comment]
> It is due to the pytorch_geometric version. Please utilize exactly the same environment as we provide

torch_geometirc has not provided the wheels of the dependencies ( such as torch_scatter 1.3.2 )  with torch_geometric 1.3.2 which only support pytorch before 1.3 , so I want to ask you how to install those dependencies in your experiment ?

**Comment by Luokejin** [comment]
Thanks, It is truely due to torch_geometric version.
