### ISSUE TITLE
Script for Meta Relation Hierarchy Tree

### ISSUE THREAD

**Issue by kexinhuang12345** [acbull/pyHGT#27]
Hi,

Thanks for the great work. I am wondering if you can provide more details about the meta relation tree (fig 5) generation? If possible, can you provide scripts to generate this tree? Thanks!

**Comment by acbull** [comment]
Hi,

In the code, I explicitly save the attention value for each forward pass (https://github.com/acbull/pyHGT/blob/63aec910d563da4538f5e84ee2802627350541fe/pyHGT/conv.py#L25), which you can plot for a given input.

For the tree, I just manually select top-K children with the highest normalized attention score for visualization. If you have further questions just ask me and I can see what I can help.

**Comment by kexinhuang12345** [comment]
Hi, thanks for the prompt reply. I am using the DGL version, is it true it corresponds to this variable? 

https://github.com/acbull/HGT-DGL/blob/182cc56a133454770a8c1043047cb44555f79853/model.py#L57

**Comment by acbull** [comment]
yes, that is the attention value.
