### ISSUE TITLE
Whole OAG Dataset

### ISSUE THREAD

**Issue by mariadiea** [acbull/pyHGT#38]
Hi @acbull 

Thank you for your work on HGT! I am currently working on extending this model and so far I have worked on the CS subgraph, but I would like to test my work on the whole graph. Would you be so kind to upload the preprocesed graph or the raw data?

**Comment by acbull** [comment]
As the whole dataset is very big, we don't have that much public disk space to share it. But one of the authors have helped to integrate Microsoft Acedamic Graph into OGB dataset (https://ogb.stanford.edu/kddcup2021/mag240m/), the preprocessing is similar to our paper. You can check it to evaluate the models.
