### ISSUE TITLE
running time of the code 

### ISSUE THREAD

**Issue by susierao** [acbull/pyHGT#4]
Hi, Thank you very much for the great repo. I am testing out the code by running:
```
$ python3 train_paper_field.py --data_dir preprocessed_OAG/ --model_dir model --conv_name hgt --cuda 1 --domain _NN --n_pool 100
```
which uses the smallest graph.. But I have kept the code running for > 10 hours and still did not manage to see the results. Am I doing things wrongly? 
And does the code support multi-gpu by wrapping model with nn.DataParallel()?
Thanks a lot.

**Comment by susierao** [comment]
Hi just to update, I ran train_paper_venue.py, which outputs results:-).

**Comment by acbull** [comment]
Hi, what do you mean you cannot see the results. For each epoch, we will output a log for training and validation error, and by default, it will run 200 epochs. You can use that to estimate the overall running time for your environment.

For multi-GPU, in principle it's feasible. You can try adding it and see whether it will decrease the running time (but still, the data preparation overhead might be a bottleneck, I notice you use n_pool=100, and I don't know whether your CPU and memory can support such large process number. Maybe you can provide your log and I can help check it for you)

**Comment by susierao** [comment]
> Hi, what do you mean you cannot see the results. For each epoch, we will output a log for training and validation error, and by default, it will run 200 epochs. You can use that to estimate the overall running time for your environment.
> 
> For multi-GPU, in principle it's feasible. You can try adding it and see whether it will decrease the running time (but still, the data preparation overhead might be a bottleneck, I notice you use n_pool=100, and I don't know whether your CPU and memory can support such large process number. Maybe you can provide your log and I can help check it for you)

**Comment by susierao** [comment]
Hi, What I meant by not seeing the results is `train_paper_field.py ` does not output results, but `train_paper_venue.py` works.
