### ISSUE TITLE
Med and OAG datasets

### ISSUE THREAD

**Issue by Weesley743** [acbull/pyHGT#5]
Hi, there seems to be only CS dataset in google drive. How can I get the Med and OAG datasets? 
I'm confused about the graph_NN and graph_ML datasets. What are their connections with the two datasets(Med,OAG) mentioned in the paper?

**Comment by Weesley743** [comment]
I use graph.node_feature['paper'] to print node features on graph_CS dataset, and the result show that there are 544243 records, but table1 in paper shown that there are 5597605 paper nodes. How to extract the features of all paper nodes? Can you give me some advice? Thank you so much.

**Comment by acbull** [comment]
Hi, as the google drive can only provide 15 GB of storage, I currently only provide CS dataset. ML and NN dataset are sub-graphs of CS datset, whose papers are fields within ML and NN. I'll consider adding Med and whole OAG later.

For the dataset scale, table 1 shown in the paper is the original scale. As shown in the pre_process.py code, I add a filter step to only consider paper whose citation above a threshold to increase the network density. You can delete that line to extract features for all paper nodes.

**Comment by Weesley743** [comment]
Thanks for your detailed reply.

**Comment by mariadiea** [comment]
> Hi, as the google drive can only provide 15 GB of storage, I currently only provide the CS dataset. ML and NN datasets are sub-graphs of the CS dataset, whose papers are fields within ML and NN. I'll consider adding Med and whole OAG later (after expanding the google drive storage).

Hi! Any updates on uploading the whole OAG dataset?
