### ISSUE TITLE
Relationship prior

### ISSUE THREAD

**Issue by AmosDinh** [acbull/pyHGT#62]
Hello, 

would you be so kind as to explain what the relationship prior is?
I looked into the code, but I do not understand that part.

Thank you

**Comment by ghost** [comment]
Hello,

Could you run the model successfully? do you mind to share the python version and the packages that you've used, please?

Thanks,
Saladin

**Comment by AmosDinh** [comment]
Hello, no I haven't run the model yet. You can use the implementation of
the python package Pytorch Geometric though

Saladin58 ***@***.***> schrieb am Fr., 13. Okt. 2023, 12:09:

**Comment by ghost** [comment]
I have used these packages as recommended but still get errors.
Python==3.7.9
dill==0.3.0
numpy==1.22.0
pandas==0.24.2
torch==1.13.1
torch-scatter==1.3.2
torch-cluster==1.4.5
torch-sparse==0.4.3
torch-spline-conv==1.1.1
torch-geometric==1.3.2
torchvision==0.4.1
tqdm==4.31.1
seaborn==0.9.0
matplotlib==3.0.3
transformers==4.30.0

**Comment by Hojan-Ye** [comment]
> I have used these packages as recommended but still get errors. Python==3.7.9 dill==0.3.0 numpy==1.22.0 pandas==0.24.2 torch==1.13.1 torch-scatter==1.3.2 torch-cluster==1.4.5 torch-sparse==0.4.3 torch-spline-conv==1.1.1 torch-geometric==1.3.2 torchvision==0.4.1 tqdm==4.31.1 seaborn==0.9.0 matplotlib==3.0.3 transformers==4.30.0

I just run the code successfully, what problem u meet. Maybe i can help u

**Comment by ghost** [comment]
Thanks for your email. I always get this error:

Traceback (most recent call last):
  File "/home/saakdr/OAG/train_paper_field.py", line 72, in <module>
    graph = renamed_load(open(os.path.join(args.data_dir, 'graph%s.pk' % args.domain), 'rb'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saakdr/OAG/pyHGT/data.py", line 272, in renamed_load
    return RenameUnpickler(file_obj).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/hpc/data/saakdr/miniconda/envs/HGT/lib/python3.11/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)



Thanks,
Best regards.
Salhuldin Alqarghuli (Saladin)
________________________________

**Comment by ghost** [comment]
> > I have used these packages as recommended but still get errors. Python==3.7.9 dill==0.3.0 numpy==1.22.0 pandas==0.24.2 torch==1.13.1 torch-scatter==1.3.2 torch-cluster==1.4.5 torch-sparse==0.4.3 torch-spline-conv==1.1.1 torch-geometric==1.3.2 torchvision==0.4.1 tqdm==4.31.1 seaborn==0.9.0 matplotlib==3.0.3 transformers==4.30.0
> 
> I just run the code successfully, what problem u meet. Maybe i can help u

I finally solved the previous error by downgrading the dill package. Now I am getting the follwing error
Have you ever had it before, please?

python train_paper_field.py --data_dir /home/saakdr/OAG/dataset --model_dir ./ --conv_name hgt --sample_depth 1 --sample_width 1 --n_pool 1 --repeat 1

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "train_paper_field.py", line 128, in node_classification_sample
    to_torch(feature, times, edge_list, graph)
  File "/home/saakdr/OAG/pyHGT/data.py", line 232, in to_torch
    node_num     += len(feature[t])
KeyError: 'affiliation'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_paper_field.py", line 224, in <module>
    train_data = [job.get() for job in jobs[:-1]]
  File "train_paper_field.py", line 224, in <listcomp>
    train_data = [job.get() for job in jobs[:-1]]
  File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'affiliation'

Thanks,
Saladin

**Comment by Hojan-Ye** [comment]
> > > I have used these packages as recommended but still get errors. Python==3.7.9 dill==0.3.0 numpy==1.22.0 pandas==0.24.2 torch==1.13.1 torch-scatter==1.3.2 torch-cluster==1.4.5 torch-sparse==0.4.3 torch-spline-conv==1.1.1 torch-geometric==1.3.2 torchvision==0.4.1 tqdm==4.31.1 seaborn==0.9.0 matplotlib==3.0.3 transformers==4.30.0
> > 
> > 
> > I just run the code successfully, what problem u meet. Maybe i can help u
> 
> I finally solved the previous error by downgrading the dill package. Now I am getting the follwing error Have you ever had it before, please?
> 
> python train_paper_field.py --data_dir /home/saakdr/OAG/dataset --model_dir ./ --conv_name hgt --sample_depth 1 --sample_width 1 --n_pool 1 --repeat 1
> 
> multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds)) File "train_paper_field.py", line 128, in node_classification_sample to_torch(feature, times, edge_list, graph) File "/home/saakdr/OAG/pyHGT/data.py", line 232, in to_torch node_num += len(feature[t]) KeyError: 'affiliation' """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "train_paper_field.py", line 224, in train_data = [job.get() for job in jobs[:-1]] File "train_paper_field.py", line 224, in train_data = [job.get() for job in jobs[:-1]] File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value KeyError: 'affiliation'
> 
> Thanks, Saladin

Sorry, I reply u late. I'm glad to see u sovle the first problem. I run the code based on Windows,  and I met a problem about the 'train_data = [job.get() for job in jobs[:-1]]', my error is not like urs. 
Here I share my expericence with u. I changed the code:  1) in 'preprocess_OAG.py', when open files, add one more  parameter about encoding, like 'line_count = sum(1 for line in open(filename, encoding='utf-8'))'. 2)in 'utils.py' some parameter about dype is too old, like 'np.srt'. So u need to check this.
Above is  how i change the code to make the code successfully run based Windows. I hope I can help u. Good luck.

**Comment by ghost** [comment]
> > > > I have used these packages as recommended but still get errors. Python==3.7.9 dill==0.3.0 numpy==1.22.0 pandas==0.24.2 torch==1.13.1 torch-scatter==1.3.2 torch-cluster==1.4.5 torch-sparse==0.4.3 torch-spline-conv==1.1.1 torch-geometric==1.3.2 torchvision==0.4.1 tqdm==4.31.1 seaborn==0.9.0 matplotlib==3.0.3 transformers==4.30.0
> > > 
> > > 
> > > I just run the code successfully, what problem u meet. Maybe i can help u
> > 
> > 
> > I finally solved the previous error by downgrading the dill package. Now I am getting the follwing error Have you ever had it before, please?
> > python train_paper_field.py --data_dir /home/saakdr/OAG/dataset --model_dir ./ --conv_name hgt --sample_depth 1 --sample_width 1 --n_pool 1 --repeat 1
> > multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds)) File "train_paper_field.py", line 128, in node_classification_sample to_torch(feature, times, edge_list, graph) File "/home/saakdr/OAG/pyHGT/data.py", line 232, in to_torch node_num += len(feature[t]) KeyError: 'affiliation' """
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "train_paper_field.py", line 224, in train_data = [job.get() for job in jobs[:-1]] File "train_paper_field.py", line 224, in train_data = [job.get() for job in jobs[:-1]] File "/home/saakdr/.conda/envs/HGT/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value KeyError: 'affiliation'
> > Thanks, Saladin
> 
> Sorry, I reply u late. I'm glad to see u sovle the first problem. I run the code based on Windows, and I met a problem about the 'train_data = [job.get() for job in jobs[:-1]]', my error is not like urs. Here I share my expericence with u. I changed the code: 1) in 'preprocess_OAG.py', when open files, add one more parameter about encoding, like 'line_count = sum(1 for line in open(filename, encoding='utf-8'))'. 2)in 'utils.py' some parameter about dype is too old, like 'np.srt'. So u need to check this. Above is how i change the code to make the code successfully run based Windows. I hope I can help u. Good luck.

Thank you so much, I really appreciate that!

**Comment by AmosDinh** [comment]
For future readers which are interested in the original question:
It was explained to me that the prior is a learnable weight.
