### ISSUE TITLE
metapath2vec and vfi_vector.tsv

### ISSUE THREAD

**Issue by susierao** [acbull/pyHGT#9]
Could you kindly share the code of generating vfi_vector.tsv for 'venue', 'field', 'affiliation' using metapath2vec? Thank you so much.

**Comment by acbull** [comment]
Hi:

The method to generate these vectors is metapath2vec: https://ericdongyx.github.io/metapath2vec/m2v.html

I didn't implement this part, as they are directly provided by the Microsoft Engineering Team, but I think you can reimplement this part using the code I sent to you.
